//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika1_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOBARS
    {
        public int ID_INFOBARS { get; set; }
        public int SUSHIBARS_ID { get; set; }
        public int SUSHISETS_ID { get; set; }
        public int CLIENTS_ID { get; set; }
    
        public virtual CLIENTS CLIENTS {private get; set; }
        public virtual SUSHIBARS SUSHIBARS {private get; set; }
        public virtual SUSHISETS SUSHISETS { private get; set; }
    }
}
