//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika1_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class praktika1_datasetEntities : DbContext
    {
        public praktika1_datasetEntities()
            : base("name=praktika1_datasetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<INFOBARS> INFOBARS { get; set; }
        public virtual DbSet<SUSHIBARS> SUSHIBARS { get; set; }
        public virtual DbSet<SUSHISETS> SUSHISETS { get; set; }
    }
}
