//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika1_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSHISETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUSHISETS()
        {
            this.INFOBARS = new HashSet<INFOBARS>();
        }
    
        public int ID_SUSHISETS { get; set; }
        public string TITLESETS { get; set; }
        public int PRICESETS { get; set; }
        public int QUANTITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFOBARS> INFOBARS { private get; set; }
    }
}
